spring:
  servlet:
    multipart:
      max-file-size: 50MB

  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL:localhost}:5432/spring
    username: root
    password: root_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  servlet:
    context-path: /api/v1/
  port: 8088

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day