replicaCount: 1

image:
  repository: rihemb/devops
  tag: latest
  pullPolicy: IfNotPresent
  
service:
  type: ClusterIP
  port: 8088

labels:
  app: my-project

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: my-project.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

